unit OperatorRequestsUnit;

interface

procedure ExecuteOperatorLinkRequest;

implementation

uses
  System.SysUtils,
  System.JSON,
  IdHTTP,
  OperatorLinksRestBrokerUnit,
  OperatorLinksHttpRequests,
  OperatorLinkUnit,
  HttpClientUnit,
  BaseResponses;

procedure ExecuteOperatorLinkRequest;
var
  Broker: TOperatorLinksRestBroker;
  ListRequest: TOperatorLinkReqList;
  ListResponse: TOperatorLinkListResponse;
  InfoRequest: TOperatorLinkReqInfo;
  InfoResponse: TOperatorLinkInfoResponse;
  NewRequest: TOperatorLinkReqNew;
  NewResponse: TIdNewResponse;
  UpdateRequest: TOperatorLinkReqUpdate;
  UpdateResponse: TJSONResponse;
  ArchiveRequest: TOperatorLinkReqArchive;
  ArchiveResponse: TJSONResponse;
  RemoveRequest: TOperatorLinkReqRemove;
  RemoveResponse: TJSONResponse;
  OperatorLink: TOperatorLink;
  CreatedLinkId: string;
  CreatedLinkName: string;
  SettingsObject: TJSONObject;
  LinkFromList: TOperatorLink;
begin
  Broker := nil;
  ListRequest := nil;
  ListResponse := nil;
  InfoRequest := nil;
  InfoResponse := nil;
  NewRequest := nil;
  NewResponse := nil;
  UpdateRequest := nil;
  UpdateResponse := nil;
  ArchiveRequest := nil;
  ArchiveResponse := nil;
  RemoveRequest := nil;
  RemoveResponse := nil;
  OperatorLink := nil;
  SettingsObject := nil;
  LinkFromList := nil;
  CreatedLinkId := '';
  CreatedLinkName := '';

  try
    Broker := TOperatorLinksRestBroker.Create('ST-Test');

    try
      ListRequest := Broker.CreateReqList as TOperatorLinkReqList;
      InfoRequest := Broker.CreateReqInfo as TOperatorLinkReqInfo;
      NewRequest := Broker.CreateReqNew as TOperatorLinkReqNew;
      UpdateRequest := Broker.CreateReqUpdate as TOperatorLinkReqUpdate;
      ArchiveRequest := Broker.CreateReqArchive as TOperatorLinkReqArchive;
      RemoveRequest := Broker.CreateReqRemove as TOperatorLinkReqRemove;

      if Assigned(NewRequest.ReqBody) and (NewRequest.ReqBody is TOperatorLink) then
      begin
        OperatorLink := TOperatorLink(NewRequest.ReqBody);
        CreatedLinkId := TGUID.NewGuid.ToString.Replace('{', '').Replace('}', '').ToLower;
        OperatorLink.Lid := CreatedLinkId;
        OperatorLink.LinkType := 'LINKOP-MSG-HOLDER';
        OperatorLink.Dir := 'input';
        OperatorLink.CompId := '85697f9f-b80d-4668-8ed2-2f70ed825eee';
        OperatorLink.DepId := '00000000-0000-0000-0000-000000000000';
        OperatorLink.Name := 'AutoTestLink_' + Copy(CreatedLinkId, 1, 8);
        OperatorLink.Caption := 'Automatically created operator link for broker demo';
        CreatedLinkName := OperatorLink.Name;
        OperatorLink.OperatorData.Autostart := True;

        SettingsObject := TJSONObject.Create;
        try
          SettingsObject.AddPair('note', 'Initial settings payload for autogenerated link');
          OperatorLink.OperatorData.Settings := SettingsObject;
        finally
          SettingsObject.Free;
        end;
      end;

      if Assigned(UpdateRequest.ReqBody) and (UpdateRequest.ReqBody is TOperatorLink) and
        Assigned(NewRequest.ReqBody) and (NewRequest.ReqBody is TOperatorLink) then
      begin
        TOperatorLink(UpdateRequest.ReqBody).Assign(TOperatorLink(NewRequest.ReqBody));
      end;

      NewResponse := Broker.New(NewRequest);

      Writeln('-----------------------------------------------------------------');
      Writeln('Operator link create request URL: ' + NewRequest.GetURLWithParams);
      Writeln(Format('Operator link create request body: %s',
        [NewRequest.ReqBodyContent]));
      Writeln('Operator link create response:');

      CreatedLinkId := '';
      if Assigned(NewResponse) and Assigned(NewResponse.ResBody) and
        not NewResponse.ResBody.ID.Trim.IsEmpty then
      begin
        CreatedLinkId := NewResponse.ResBody.ID;
        Writeln('Created operator link ID: ' + CreatedLinkId);
      end
      else
        Writeln('Operator link identifier was not returned in the response.');

      if not CreatedLinkId.IsEmpty then
      begin
        UpdateRequest.Id := CreatedLinkId;

        if Assigned(UpdateRequest.ReqBody) and (UpdateRequest.ReqBody is TOperatorLink) then
        begin
          OperatorLink := TOperatorLink(UpdateRequest.ReqBody);
          OperatorLink.Name := CreatedLinkName + '_Updated';
          OperatorLink.Caption := 'Automatically updated operator link caption';
          OperatorLink.OperatorData.Autostart := False;

          SettingsObject := TJSONObject.Create;
          try
            SettingsObject.AddPair('note', 'Updated settings payload for autogenerated link');
            SettingsObject.AddPair('retries', TJSONNumber.Create(3));
            OperatorLink.OperatorData.Settings := SettingsObject;
          finally
            SettingsObject.Free;
          end;
        end;

        UpdateResponse := Broker.Update(UpdateRequest);

        Writeln('-----------------------------------------------------------------');
        Writeln('Operator link update request URL: ' + UpdateRequest.GetURLWithParams);
        Writeln(Format('Operator link update request body: %s',
          [UpdateRequest.ReqBodyContent]));
        Writeln('Operator link update response:');
        if Assigned(UpdateResponse) and not UpdateResponse.Response.Trim.IsEmpty then
          Writeln(UpdateResponse.Response)
        else
          Writeln('(empty response body)');

        InfoRequest.Id := CreatedLinkId;
        FreeAndNil(InfoResponse);
        InfoResponse := Broker.Info(InfoRequest);

        Writeln('-----------------------------------------------------------------');
        Writeln('Operator link info request URL: ' + InfoRequest.GetURLWithParams);
        Writeln('Operator link info response after update:');

        if Assigned(InfoResponse) and Assigned(InfoResponse.Link) then
        begin
          OperatorLink := InfoResponse.Link;
          Writeln(Format('Name: %s', [OperatorLink.Name]));
          Writeln(Format('Type: %s', [OperatorLink.LinkType]));
          Writeln(Format('Status: %s', [OperatorLink.Status]));
          Writeln(Format('Connection status: %s', [OperatorLink.Comsts]));
          Writeln(Format('Last activity time: %d',
            [OperatorLink.LastActivityTime]));
        end
        else
          Writeln('Operator link details were not returned in the response.');

        ArchiveRequest.Id := CreatedLinkId;
        ArchiveResponse := Broker.Archive(ArchiveRequest);

        Writeln('-----------------------------------------------------------------');
        Writeln('Operator link archive request URL: ' + ArchiveRequest.GetURLWithParams);
        Writeln('Operator link archive response:');
        if Assigned(ArchiveResponse) and not ArchiveResponse.Response.Trim.IsEmpty then
          Writeln(ArchiveResponse.Response)
        else
          Writeln('(empty response body)');

        RemoveRequest.Id := CreatedLinkId;
        RemoveResponse := Broker.Remove(RemoveRequest);

        Writeln('-----------------------------------------------------------------');
        Writeln('Operator link remove request URL: ' + RemoveRequest.GetURLWithParams);
        Writeln('Operator link remove response:');
        if Assigned(RemoveResponse) and not RemoveResponse.Response.Trim.IsEmpty then
          Writeln(RemoveResponse.Response)
        else
          Writeln('(empty response body)');
      end;

//      ListRequest.SetCount(5);
//      ListRequest.SetFlags(['body']);
      ListResponse := Broker.List(ListRequest);

      Writeln('-----------------------------------------------------------------');
      Writeln('Operator link list request URL: ' + ListRequest.GetURLWithParams);
      Writeln('Operator link list response:');
      if Assigned(ListResponse) and Assigned(ListResponse.LinkList) then
      begin
        Writeln(Format('Operator links returned: %d',
          [ListResponse.LinkList.Count]));

        if ListResponse.LinkList.Count > 0 then
        begin
          LinkFromList := TOperatorLink(ListResponse.LinkList[0]);
          Writeln(Format('First operator link: %s (%s)',
            [LinkFromList.Name, LinkFromList.Lid]));
        end;
      end
      else
        Writeln('Operator link list response was empty.');
    except
      on E: EIdHTTPProtocolException do
      begin
        Writeln(Format('Error : %d %s', [E.ErrorCode, E.ErrorMessage]));
      end;
      on E: Exception do
      begin
        Writeln('Error: ' + E.Message);
      end;
    end;
  finally
    RemoveResponse.Free;
    RemoveRequest.Free;
    ArchiveResponse.Free;
    ArchiveRequest.Free;
    UpdateResponse.Free;
    UpdateRequest.Free;
    NewResponse.Free;
    NewRequest.Free;
    InfoResponse.Free;
    InfoRequest.Free;
    ListResponse.Free;
    ListRequest.Free;
    Broker.Free;
  end;
end;

end.
