program frontDCC;

uses
  Forms,
  ServerModule in 'ServerModule.pas' {UniServerModule: TUniGUIServerModule},
  MainModule in 'MainModule.pas' {UniMainModule: TUniGUIMainModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  LoggingUnit in '..\logging\LoggingUnit.pas',
  ContextTypeUnit in '..\services\dataserver\entities\ContextTypeUnit.pas',
  ContextUnit in '..\services\dataserver\entities\ContextUnit.pas',
  LocationUnit in '..\services\dataserver\entities\LocationUnit.pas',
  SourceUnit in '..\services\dataserver\entities\SourceUnit.pas',
  DepartmentUnit in '..\services\acl\entities\DepartmentUnit.pas',
  FuncUnit in '..\common\FuncUnit.pas',
  GUIDListUnit in '..\common\GUIDListUnit.pas',
  StringListUnit in '..\common\StringListUnit.pas',
  APIConst in '..\services\common\brokers\APIConst.pas',
  BaseRequests in '..\services\common\brokers\BaseRequests.pas',
  BaseResponses in '..\services\common\brokers\BaseResponses.pas',
  HttpClientUnit in '..\services\common\brokers\HttpClientUnit.pas',
  RestBrokerBaseUnit in '..\services\common\brokers\RestBrokerBaseUnit.pas',
  RestEntityBrokerUnit in '..\services\common\brokers\RestEntityBrokerUnit.pas',
  CompaniesRestBrokerUnit in '..\services\acl\brokers\CompaniesRestBrokerUnit.pas',
  CompanyHttpRequests in '..\services\acl\brokers\CompanyHttpRequests.pas',
  DepartmentsRestBrokerUnit in '..\services\acl\brokers\DepartmentsRestBrokerUnit.pas',
  ParentEditFormUnit in '..\forms\common\ParentEditFormUnit.pas' {ParentEditForm: TUniForm},
  ParentFormUnit in '..\forms\common\ParentFormUnit.pas' {ParentForm: TUniForm},
  ConstsUnit in '..\common\ConstsUnit.pas',
  LinkFrameUtils in '..\forms\links\LinksFrames\LinkFrameUtils.pas',
  LinkEditFormUnit in '..\forms\links\LinkEditFormUnit.pas' {LinkEditForm: TUniForm},
  LinkSettingsFormUnit in '..\forms\links\LinkSettingsFormUnit.pas' {LinkSettingsForm: TUniForm},
  ListParentFormUnit in '..\forms\common\ListParentFormUnit.pas' {ListParentForm: TUniForm},
  LinksFormUnit in '..\forms\links\LinksFormUnit.pas' {LinksForm: TUniForm},
  LinksHttpRequests in '..\services\datacomm\brokers\LinksHttpRequests.pas',
  LinksRestBrokerUnit in '..\services\datacomm\brokers\LinksRestBrokerUnit.pas',
  ConnectionSettingsUnit in '..\services\datacomm\entities\ConnectionSettingsUnit.pas',
  DirSettingsUnit in '..\services\datacomm\entities\DirSettingsUnit.pas',
  LinkSettingsUnit in '..\services\datacomm\entities\LinkSettingsUnit.pas',
  LinkUnit in '..\services\datacomm\entities\LinkUnit.pas',
  S3SettingsUnit in '..\services\datacomm\entities\S3SettingsUnit.pas',
  ScheduleSettingsUnit in '..\services\datacomm\entities\ScheduleSettingsUnit.pas',
  SharedFrameTextInput in '..\forms\links\LinksFrames\SharedFrameTextInput.pas' {FrameTextInput: TUniFrame},
  SharedFrameCombobox in '..\forms\links\LinksFrames\SharedFrameCombobox.pas' {FrameCombobox: TUniFrame},
  SharedFrameBoolInput in '..\forms\links\LinksFrames\SharedFrameBoolInput.pas' {FrameBoolInput: TUniFrame},
  ParentLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\ParentLinkSettingEditFrameUnit.pas' {ParentLinkSettingEditFrame: TUniFrame},
  ProfilesFrameUnit in '..\forms\links\LinksFrames\ProfilesFrameUnit.pas' {ProfilesFrame: TUniFrame},
  ProfileFrameUnit in '..\forms\links\LinksFrames\ProfileFrameUnit.pas' {ProfileFrame: TUniFrame},
  SharedFrameRuleConditionUnit in '..\forms\links\LinksFrames\SharedFrameRuleConditionUnit.pas' {FrameRuleCondition: TUniFrame},
  KeyValUnit in '..\common\KeyValUnit.pas',
  ConditionUnit in '..\services\common\entities\ConditionUnit.pas',
  EntityUnit in '..\services\common\entities\EntityUnit.pas',
  FilterUnit in '..\services\common\entities\FilterUnit.pas',
  ProfileUnit in '..\services\datacomm\entities\ProfileUnit.pas',
  ProfileRuleUnit in '..\services\datacomm\entities\ProfileRuleUnit.pas',
  ProfilesRestBrokerUnit in '..\services\datacomm\brokers\ProfilesRestBrokerUnit.pas',
  ProfileHttpRequests in '..\services\datacomm\brokers\ProfileHttpRequests.pas',
  common in '..\common\common.pas',
  SharedFrameConnections in '..\forms\links\LinksFrames\SharedFrameConnections.pas' {FrameConnections: TUniFrame},
  SharedFrameSchedule in '..\forms\links\LinksFrames\SharedFrameSchedule.pas' {FrameSchedule: TUniFrame},
  SharedFrameS3 in '..\forms\links\LinksFrames\SharedFrameS3.pas' {FrameS3: TUniFrame},
  HTTPCliDownLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\HTTPCliDownLinkSettingEditFrameUnit.pas' {HTTPCliDownLinkSettingEditFrame: TUniFrame},
  SebaCSDLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\SebaCSDLinkSettingEditFrameUnit.pas' {SebaCSDLinkSettingEditFrame: TUniFrame},
  SebaSGSLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\SebaSGSLinkSettingEditFrameUnit.pas' {SebaSGSLinkSettingEditFrame: TUniFrame},
  SourcesFormUnit in '..\forms\sources\SourcesFormUnit.pas' {SourcesForm: TUniForm},
  SourceEditFormUnit in '..\forms\sources\SourceEditFormUnit.pas' {SourceEditForm: TUniForm},
  IntefraceEditFormUnit in '..\forms\sources\IntefraceEditFormUnit.pas' {InterfaceModalForm: TUniForm},
  ObservationFormUnit in '..\forms\observation\ObservationFormUnit.pas' {ObservationForm: TUniForm},
  SourceCredsUnit in '..\services\dataserver\entities\SourceCredsUnit.pas',
  ContextCreateFormUnit in '..\forms\sources\ContextCreateFormUnit.pas' {ContextCreateForm: TUniForm},
  ContextsHttpRequests in '..\services\dataserver\brokers\ContextsHttpRequests.pas',
  ContextsRestBrokerUnit in '..\services\dataserver\brokers\ContextsRestBrokerUnit.pas',
  LocationHttpRequests in '..\services\dataserver\brokers\LocationHttpRequests.pas',
  LocationsRestBrokerUnit in '..\services\dataserver\brokers\LocationsRestBrokerUnit.pas',
  OrganizationHttpRequests in '..\services\dataserver\brokers\OrganizationHttpRequests.pas',
  OrganizationsRestBrokerUnit in '..\services\dataserver\brokers\OrganizationsRestBrokerUnit.pas',
  SourceCredsHttpRequests in '..\services\dataserver\brokers\SourceCredsHttpRequests.pas',
  SourceCredsRestBrokerUnit in '..\services\dataserver\brokers\SourceCredsRestBrokerUnit.pas',
  SourceHttpRequests in '..\services\dataserver\brokers\SourceHttpRequests.pas',
  SourcesRestBrokerUnit in '..\services\dataserver\brokers\SourcesRestBrokerUnit.pas',
  TaskEditParentFormUnit in '..\forms\tasks\TaskEditParentFormUnit.pas' {TaskEditParentForm: TUniForm},
  TasksParentFormUnit in '..\forms\tasks\TasksParentFormUnit.pas' {TaskParentForm: TUniForm},
  ParentTaskCustomSettingsEditFrameUnit in '..\forms\tasks\TasksFrames\ParentTaskCustomSettingsEditFrameUnit.pas' {ParentTaskCustomSettingsEditFrame: TUniFrame},
  SummaryCXMLTaskCustomSettingsEditFrameUnit in '..\forms\summary\TasksFrames\SummaryCXMLTaskCustomSettingsEditFrameUnit.pas' {SummaryCXMLTaskCustomSettingsEditFrame: TUniFrame},
  SummaryHydraTaskCustomSettingsEditFrameUnit in '..\forms\summary\TasksFrames\SummaryHydraTaskCustomSettingsEditFrameUnit.pas' {SummaryHydraTaskCustomSettingsEditFrame: TUniFrame},
  SummarySEBATaskCustomSettingsEditFrameUnit in '..\forms\summary\TasksFrames\SummarySEBATaskCustomSettingsEditFrameUnit.pas' {SummarySEBATaskCustomSettingsEditFrame: TUniFrame},
  SummarySynopTaskCustomSettingsEditFrameUnit in '..\forms\summary\TasksFrames\SummarySynopTaskCustomSettingsEditFrameUnit.pas' {SummarySynopTaskCustomSettingsEditFrame: TUniFrame},
  DSProcessorTaskEditFormUnit in '..\forms\dsproc\DSProcessorTaskEditFormUnit.pas' {DSProcessorTaskEditForm: TUniForm},
  DSProcessorTasksFormUnit in '..\forms\dsproc\DSProcessorTasksFormUnit.pas' {DSProcessorTasksForm: TUniForm},
  MonitoringTaskEditFormUnit in '..\forms\monitoring\MonitoringTaskEditFormUnit.pas' {MonitoringTaskEditForm: TUniForm},
  MonitoringTasksFormUnit in '..\forms\monitoring\MonitoringTasksFormUnit.pas' {MonitoringTasksForm: TUniForm},
  StripTaskEditFormUnit in '..\forms\strip\StripTaskEditFormUnit.pas' {StripTaskEditForm: TUniForm},
  StripTasksFormUnit in '..\forms\strip\StripTasksFormUnit.pas' {StripTasksForm: TUniForm},
  SummaryTaskEditFormUnit in '..\forms\summary\SummaryTaskEditFormUnit.pas' {SummaryTaskEditForm: TUniForm},
  SummaryTasksFormUnit in '..\forms\summary\SummaryTasksFormUnit.pas' {SummaryTasksForm: TUniForm},
  SummaryTaskUnit in '..\services\summary\entities\SummaryTaskUnit.pas',
  SummaryTaskCustomSettingsUnit in '..\services\summary\entities\SummaryTaskCustomSettingsUnit.pas',
  SelectTaskSourcesFormUnit in '..\forms\tasks\SelectTaskSourcesFormUnit.pas' {SelectTaskSourcesForm: TUniForm},
  TaskSettingsUnit in '..\services\tasks\entities\TaskSettingsUnit.pas',
  TaskSourceUnit in '..\services\tasks\entities\TaskSourceUnit.pas',
  TaskUnit in '..\services\tasks\entities\TaskUnit.pas',
  TaskTypesUnit in '..\services\tasks\entities\TaskTypesUnit.pas',
  TaskHttpRequests in '..\services\tasks\brokers\TaskHttpRequests.pas',
  TaskSourcesRestBrokerUnit in '..\services\tasks\brokers\TaskSourcesRestBrokerUnit.pas',
  StripTaskUnit in '..\services\strip\entities\StripTaskUnit.pas',
  MonitoringTaskUnit in '..\services\monitoring\entities\MonitoringTaskUnit.pas',
  DSProcessorTaskUnit in '..\services\dsproc\entities\DSProcessorTaskUnit.pas',
  CompanyUnit in '..\services\acl\entities\CompanyUnit.pas',
  OrganizationUnit in '..\services\dataserver\entities\OrganizationUnit.pas',
  DepartmentHttpRequests in '..\services\acl\brokers\DepartmentHttpRequests.pas',
  TasksRestBrokerUnit in '..\services\tasks\brokers\TasksRestBrokerUnit.pas',
  SummaryTasksRestBrokerUnit in '..\services\summary\brokers\SummaryTasksRestBrokerUnit.pas',
  TaskSourceHttpRequests in '..\services\tasks\brokers\TaskSourceHttpRequests.pas',
  SummaryTasksHttpRequests in '..\services\summary\brokers\SummaryTasksHttpRequests.pas',
  StringUnit in '..\services\common\entities\StringUnit.pas',
  DirDownSettingEditFrameUnit in '..\forms\links\LinksFrames\DirDownSettingEditFrameUnit.pas' {DirDownSettingEditFrame: TUniFrame},
  FTPServerDownLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\FTPServerDownLinkSettingEditFrameUnit.pas' {FTPServerDownLinkSettingEditFrame: TUniFrame},
  SMTPSrvDownLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\SMTPSrvDownLinkSettingEditFrameUnit.pas' {SMTPSrvDownLinkSettingEditFrame: TUniFrame},
  RestFieldSetBrokerUnit in '..\services\common\brokers\RestFieldSetBrokerUnit.pas',
  UniStorageHelpers in '..\common\UniStorageHelpers.pas',
  AuthMainFormUnit in '..\forms\common\AuthMainFormUnit.pas' {AuthMainForm: TUniForm},
  EmbedLoginFormUnit in '..\forms\common\EmbedLoginFormUnit.pas',
  FormLayoutFormUnit in '..\forms\common\FormLayoutFormUnit.pas',
  AppConfigUnit in '..\common\AppConfigUnit.pas',
  CasHttpRequests in '..\services\acl\cas\brokers\CasHttpRequests.pas',
  CasRestBrokerUnit in '..\services\acl\cas\brokers\CasRestBrokerUnit.pas',
  HttpProtocolExceptionHelper in '..\services\common\brokers\HttpProtocolExceptionHelper.pas',
  SessionHttpRequests in '..\services\acl\brokers\SessionHttpRequests.pas',
  SessionsRestBrokerUnit in '..\services\acl\brokers\SessionsRestBrokerUnit.pas',
  SessionUnit in '..\services\acl\entities\SessionUnit.pas',
  UserUnit in '..\services\acl\entities\UserUnit.pas',
  MainModuleBaseUnit in '..\common\MainModuleBaseUnit.pas';

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  TUniServerModule.Create(Application);
  Application.Run;
end.
