program frontMSS;

uses
  Forms,
  ServerModule in 'ServerModule.pas' {UniServerModule: TUniGUIServerModule},
  MainModule in 'MainModule.pas' {UniMainModule: TUniGUIMainModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  CompanyUnit in '..\services\acl\entities\CompanyUnit.pas',
  DepartmentUnit in '..\services\acl\entities\DepartmentUnit.pas',
  UserUnit in '..\services\acl\entities\UserUnit.pas',
  SessionUnit in '..\services\acl\entities\SessionUnit.pas',
  EntityUnit in '..\services\common\entities\EntityUnit.pas',
  FuncUnit in '..\common\FuncUnit.pas',
  AppConfigUnit in '..\common\AppConfigUnit.pas',
  LoggingUnit in '..\logging\LoggingUnit.pas',
  GUIDListUnit in '..\common\GUIDListUnit.pas',
  StringListUnit in '..\common\StringListUnit.pas',
  StringUnit in '..\services\common\entities\StringUnit.pas',
  CompaniesRestBrokerUnit in '..\services\acl\brokers\CompaniesRestBrokerUnit.pas',
  CompanyHttpRequests in '..\services\acl\brokers\CompanyHttpRequests.pas',
  DepartmentHttpRequests in '..\services\acl\brokers\DepartmentHttpRequests.pas',
  DepartmentsRestBrokerUnit in '..\services\acl\brokers\DepartmentsRestBrokerUnit.pas',
  SessionHttpRequests in '..\services\acl\brokers\SessionHttpRequests.pas',
  SessionsRestBrokerUnit in '..\services\acl\brokers\SessionsRestBrokerUnit.pas',
  APIConst in '..\services\common\brokers\APIConst.pas',
  BaseRequests in '..\services\common\brokers\BaseRequests.pas',
  BaseResponses in '..\services\common\brokers\BaseResponses.pas',
  HttpClientUnit in '..\services\common\brokers\HttpClientUnit.pas',
  RestBrokerBaseUnit in '..\services\common\brokers\RestBrokerBaseUnit.pas',
  RestEntityBrokerUnit in '..\services\common\brokers\RestEntityBrokerUnit.pas',
  CasRestBrokerUnit in '..\services\acl\cas\brokers\CasRestBrokerUnit.pas',
  CasHttpRequests in '..\services\acl\cas\brokers\CasHttpRequests.pas',
  HttpProtocolExceptionHelper in '..\services\common\brokers\HttpProtocolExceptionHelper.pas',
  ConstsUnit in '..\common\ConstsUnit.pas',
  ChannelEditFormUnit in '..\forms\channels\ChannelEditFormUnit.pas' {ChannelEditForm: TUniForm},
  ChannelsFormUnit in '..\forms\channels\ChannelsFormUnit.pas' {ChannelsForm: TUniForm},
  AbonentUnit in '..\services\router\entities\AbonentUnit.pas',
  AliasUnit in '..\services\router\entities\AliasUnit.pas',
  ChannelUnit in '..\services\router\entities\ChannelUnit.pas',
  HandlerUnit in '..\services\router\entities\HandlerUnit.pas',
  QueueUnit in '..\services\router\entities\QueueUnit.pas',
  RouterSourceUnit in '..\services\router\entities\RouterSourceUnit.pas',
  LinkEditFormUnit in '..\forms\links\LinkEditFormUnit.pas' {LinkEditForm: TUniForm},
  LinksFormUnit in '..\forms\links\LinksFormUnit.pas' {LinksForm: TUniForm},
  OperatorLinkEditFormUnit in '..\forms\operatorLinks\OperatorLinkEditFormUnit.pas' {OperatorLinkEditForm: TUniForm},
  OperatorLinksFormUnit in '..\forms\operatorLinks\OperatorLinksFormUnit.pas' {OperatorLinksForm: TUniForm},
  OperatorLinkContectFormUnit in '..\forms\operatorLinksContent\OperatorLinkContectFormUnit.pas' {OperatorLinkContectForm: TUniForm},
  ContentViewFormUnit in '..\forms\contentView\ContentViewFormUnit.pas' {ContentViewForm: TUniForm},
  ContentStreamFormUnit in '..\forms\contentStream\ContentStreamFormUnit.pas' {ContentStreamForm: TUniForm},
  SearchFormUnit in '..\forms\search\SearchFormUnit.pas' {SearchForm: TUniForm},
  ParentLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\ParentLinkSettingEditFrameUnit.pas' {ParentLinkSettingEditFrame: TUniFrame},
  ProfilesFrameUnit in '..\forms\links\LinksFrames\ProfilesFrameUnit.pas' {ProfilesFrame: TUniFrame},
  ProfileFrameUnit in '..\forms\links\LinksFrames\ProfileFrameUnit.pas' {ProfileFrame: TUniFrame},
  SharedFrameBoolInput in '..\forms\links\LinksFrames\SharedFrameBoolInput.pas' {FrameBoolInput: TUniFrame},
  SharedFrameCombobox in '..\forms\links\LinksFrames\SharedFrameCombobox.pas' {FrameCombobox: TUniFrame},
  SharedFrameTextInput in '..\forms\links\LinksFrames\SharedFrameTextInput.pas' {FrameTextInput: TUniFrame},
  KeyValUnit in '..\common\KeyValUnit.pas',
  LinkUnit in '..\services\datacomm\entities\LinkUnit.pas',
  LinkSettingsUnit in '..\services\datacomm\entities\LinkSettingsUnit.pas',
  ConnectionSettingsUnit in '..\services\datacomm\entities\ConnectionSettingsUnit.pas',
  DirSettingsUnit in '..\services\datacomm\entities\DirSettingsUnit.pas',
  S3SettingsUnit in '..\services\datacomm\entities\S3SettingsUnit.pas',
  ScheduleSettingsUnit in '..\services\datacomm\entities\ScheduleSettingsUnit.pas',
  ConditionUnit in '..\services\common\entities\ConditionUnit.pas',
  FilterUnit in '..\services\common\entities\FilterUnit.pas',
  ProfileRuleUnit in '..\services\datacomm\entities\ProfileRuleUnit.pas',
  ProfileUnit in '..\services\datacomm\entities\ProfileUnit.pas',
  LinksHttpRequests in '..\services\datacomm\brokers\LinksHttpRequests.pas',
  LinksRestBrokerUnit in '..\services\datacomm\brokers\LinksRestBrokerUnit.pas',
  ProfileHttpRequests in '..\services\datacomm\brokers\ProfileHttpRequests.pas',
  ProfilesRestBrokerUnit in '..\services\datacomm\brokers\ProfilesRestBrokerUnit.pas',
  LinkFrameUtils in '..\forms\links\LinksFrames\LinkFrameUtils.pas',
  SharedFrameConnections in '..\forms\links\LinksFrames\SharedFrameConnections.pas' {FrameConnections: TUniFrame},
  SharedFrameRuleConditionUnit in '..\forms\links\LinksFrames\SharedFrameRuleConditionUnit.pas' {FrameRuleCondition: TUniFrame},
  SharedFrameS3 in '..\forms\links\LinksFrames\SharedFrameS3.pas' {FrameS3: TUniFrame},
  SharedFrameSchedule in '..\forms\links\LinksFrames\SharedFrameSchedule.pas' {FrameSchedule: TUniFrame},
  common in '..\common\common.pas',
  SharedFrameQueue in '..\forms\links\LinksFrames\SharedFrameQueue.pas' {FrameQueue: TUniFrame},
  DirDownSettingEditFrameUnit in '..\forms\links\LinksFrames\DirDownSettingEditFrameUnit.pas' {DirDownSettingEditFrame: TUniFrame},
  DirUpSettingEditFrameUnit in '..\forms\links\LinksFrames\DirUpSettingEditFrameUnit.pas' {DirUpSettingEditFrame: TUniFrame},
  FTPCliDownLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\FTPCliDownLinkSettingEditFrameUnit.pas' {FtpCliDownLinkSettingEditFrame: TUniFrame},
  FTPCliUpLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\FTPCliUpLinkSettingEditFrameUnit.pas' {FTPCliUpLinkSettingEditFrame: TUniFrame},
  FTPServerDownLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\FTPServerDownLinkSettingEditFrameUnit.pas' {FTPServerDownLinkSettingEditFrame: TUniFrame},
  FTPSrvUpLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\FTPSrvUpLinkSettingEditFrameUnit.pas' {FTPSrvUpLinkSettingEditFrame: TUniFrame},
  OpenMCEPSettingEditFrameUnit in '..\forms\links\LinksFrames\OpenMCEPSettingEditFrameUnit.pas' {OpenMCEPSettingEditFrame: TUniFrame},
  Pop3CliDownLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\Pop3CliDownLinkSettingEditFrameUnit.pas' {Pop3CliDownLinkSettingEditFrame: TUniFrame},
  SMTPClieUpLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\SMTPClieUpLinkSettingEditFrameUnit.pas' {SMTPClieUpLinkSettingEditFrame: TUniFrame},
  SMTPSrvDownLinkSettingEditFrameUnit in '..\forms\links\LinksFrames\SMTPSrvDownLinkSettingEditFrameUnit.pas' {SMTPSrvDownLinkSettingEditFrame: TUniFrame},
  SocketSpecialSettingEditFrameUnit in '..\forms\links\LinksFrames\SocketSpecialSettingEditFrameUnit.pas' {SocketSpecialSettingEditFrame: TUniFrame},
  QueueSettingsUnit in '..\services\datacomm\entities\QueueSettingsUnit.pas',
  QueueEditFormUnit in '..\forms\queues\QueueEditFormUnit.pas' {QueueEditForm: TUniForm},
  QueuesFormUnit in '..\forms\queues\QueuesFormUnit.pas' {QueuesForm: TUniForm},
  AbonentEditFormUnit in '..\forms\abonents\AbonentEditFormUnit.pas' {AbonentEditForm: TUniForm},
  AbonentsFormUnit in '..\forms\abonents\AbonentsFormUnit.pas' {AbonentsForm: TUniForm},
  AliasEditFormUnit in '..\forms\aliases\AliasEditFormUnit.pas' {AliasEditForm: TUniForm},
  AliasesFormUnit in '..\forms\aliases\AliasesFormUnit.pas' {AliasesForm: TUniForm},
  RouterSourceEditFormUnit in '..\forms\routerSources\RouterSourceEditFormUnit.pas' {RouterSourceEditForm: TUniForm},
  RouterSourcesFormUnit in '..\forms\routerSources\RouterSourcesFormUnit.pas' {RouterSourcesForm: TUniForm},
  RuleEditFormUnit in '..\forms\rules\RuleEditFormUnit.pas' {RuleEditForm: TUniForm},
  RulesFormUnit in '..\forms\rules\RulesFormUnit.pas' {RulesForm: TUniForm},
  HandlerEditFormUnit in '..\forms\handlers\HandlerEditFormUnit.pas' {HandlerEditForm: TUniForm},
  HandlersFormUnit in '..\forms\handlers\HandlersFormUnit.pas' {HandlersForm: TUniForm},
  AbonentHttpRequests in '..\services\router\brokers\AbonentHttpRequests.pas',
  AbonentsRestBrokerUnit in '..\services\router\brokers\AbonentsRestBrokerUnit.pas',
  AliasesRestBrokerUnit in '..\services\router\brokers\AliasesRestBrokerUnit.pas',
  AliasHttpRequests in '..\services\router\brokers\AliasHttpRequests.pas',
  ChannelHttpRequests in '..\services\router\brokers\ChannelHttpRequests.pas',
  ChannelsRestBrokerUnit in '..\services\router\brokers\ChannelsRestBrokerUnit.pas',
  QueueHttpRequests in '..\services\router\brokers\QueueHttpRequests.pas',
  QueuesRestBrokerUnit in '..\services\router\brokers\QueuesRestBrokerUnit.pas',
  RouterSourceHttpRequests in '..\services\router\brokers\RouterSourceHttpRequests.pas',
  RouterSourcesRestBrokerUnit in '..\services\router\brokers\RouterSourcesRestBrokerUnit.pas',
  HandlerHttpRequests in '..\services\router\brokers\HandlerHttpRequests.pas',
  HandlersRestBrokerUnit in '..\services\router\brokers\HandlersRestBrokerUnit.pas',
  RuleHttpRequests in '..\services\router\brokers\RuleHttpRequests.pas',
  RulesRestBrokerUnit in '..\services\router\brokers\RulesRestBrokerUnit.pas',
  RuleUnit in '..\services\router\entities\RuleUnit.pas',
  SmallRuleUnit in '..\services\router\entities\SmallRuleUnit.pas',
  QueueFrameUnit in '..\forms\channels\QueueFrameUnit.pas' {QueueFrame: TUniFrame},
  SharedFrameQueueFilterUnit in '..\forms\channels\SharedFrameQueueFilterUnit.pas' {QueueConditionFrame: TUniFrame},
  OperatorLinkUnit in '..\services\linkop\entities\OperatorLinkUnit.pas',
  OperatorLinksHttpRequests in '..\services\linkop\brokers\OperatorLinksHttpRequests.pas',
  OperatorLinksRestBrokerUnit in '..\services\linkop\brokers\OperatorLinksRestBrokerUnit.pas',
  OperatorLinksContentHttpRequests in '..\services\linkop\brokers\OperatorLinksContentHttpRequests.pas',
  OperatorLinksContentRestBrokerUnit in '..\services\linkop\brokers\OperatorLinksContentRestBrokerUnit.pas',
  RestFieldSetBrokerUnit in '..\services\common\brokers\RestFieldSetBrokerUnit.pas',
  HistoryRecordUnit in '..\services\dataspace\entities\HistoryRecordUnit.pas',
  JournalRecordsAttrsUnit in '..\services\dataspace\entities\JournalRecordsAttrsUnit.pas',
  JournalRecordUnit in '..\services\dataspace\entities\JournalRecordUnit.pas',
  HistoryRecordsRestBrokerUnit in '..\services\dataspace\brokers\HistoryRecordsRestBrokerUnit.pas',
  HistoryRecordHttpRequests in '..\services\dataspace\brokers\HistoryRecordHttpRequests.pas',
  SearchRestBrokerUnit in '..\services\dataspace\brokers\SearchRestBrokerUnit.pas',
  SearchUnit in '..\services\dataspace\entities\SearchUnit.pas',
  SearchHttpRequests in '..\services\dataspace\brokers\SearchHttpRequests.pas',
  StorageHttpRequests in '..\services\dataspace\brokers\StorageHttpRequests.pas',
  StorageRestBrokerUnit in '..\services\dataspace\brokers\StorageRestBrokerUnit.pas',
  UniStorageHelpers in '..\common\UniStorageHelpers.pas',
  AuthMainFormUnit in '..\forms\common\AuthMainFormUnit.pas' {AuthMainForm: TUniForm},
  EmbedLoginFormUnit in '..\forms\common\EmbedLoginFormUnit.pas' {EmbedLoginForm: TUniForm},
  FormLayoutFormUnit in '..\forms\common\FormLayoutFormUnit.pas' {FormLayout: TUniForm},
  ListParentFormUnit in '..\forms\common\ListParentFormUnit.pas' {ListParentForm: TUniForm},
  ParentEditFormUnit in '..\forms\common\ParentEditFormUnit.pas' {ParentEditForm: TUniForm},
  ParentFormUnit in '..\forms\common\ParentFormUnit.pas' {ParentForm: TUniForm};

{$R *.res}

begin
  ReportMemoryLeaksOnShutdown := True;
  Application.Initialize;
  TUniServerModule.Create(Application);
  Application.Run;
end.
